/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_test;

/**
 *
 * @author Venga
 */
public class Test_form_ extends javax.swing.JFrame {

    /**
     * Creates new form Test_form_
     */
    public Test_form_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carAudio = new javax.swing.JCheckBox();
        carBMW = new javax.swing.JCheckBox();
        carHonda = new javax.swing.JCheckBox();
        Labelstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        carAudio.setText("Audio");
        carAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carAudioActionPerformed(evt);
            }
        });

        carBMW.setText("BMW");
        carBMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBMWActionPerformed(evt);
            }
        });

        carHonda.setText("Honda");
        carHonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carHondaActionPerformed(evt);
            }
        });

        Labelstatus.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carHonda)
                            .addComponent(carBMW)
                            .addComponent(carAudio)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Labelstatus)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(carAudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carBMW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carHonda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(Labelstatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void checkForm()
    {
        StringBuffer a = new StringBuffer();
        if(carAudio.isSelected())
        {
            a.append("Audio");
        }
        if(carBMW.isSelected())
        {
            a.append("car BMW");
        }
        if(carHonda.isSelected())
        {
            a.append("Car Honda");
        }
        Labelstatus.setText(a.toString());
    }
    private void carAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carAudioActionPerformed
         checkForm();
        // TODO add your handling code here:
    }//GEN-LAST:event_carAudioActionPerformed

    private void carBMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBMWActionPerformed
        checkForm();
        // TODO add your handling code here:
    }//GEN-LAST:event_carBMWActionPerformed

    private void carHondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carHondaActionPerformed
          checkForm();
        // TODO add your handling code here:
    }//GEN-LAST:event_carHondaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test_form_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test_form_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test_form_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test_form_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test_form_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelstatus;
    private javax.swing.JCheckBox carAudio;
    private javax.swing.JCheckBox carBMW;
    private javax.swing.JCheckBox carHonda;
    // End of variables declaration//GEN-END:variables
}
