/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai_Tap;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
//import java.util.Locale;

//Print data from jtable to PDF Library;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import javax.swing.JFileChooser;
import com.itextpdf.text.Document;
import com.mysql.cj.result.Row;


//poi with excel;
import java.io.FileOutputStream;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
public class JFrame_Bai_Hoa_Don extends javax.swing.JFrame {


    public JFrame_Bai_Hoa_Don() {
        initComponents();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-YYYY");
        Date date = new Date();
        Lb_Date.setText(dFormat.format(date));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lb_Time.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lb_Date = new javax.swing.JLabel();
        lb_Time = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_so_thu_tu = new javax.swing.JTextField();
        txt_Diachi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_Dien_thoai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Ten = new javax.swing.JTextField();
        txt_MaHang = new javax.swing.JTextField();
        txt_Don_Vi = new javax.swing.JTextField();
        txt_Don_gia = new javax.swing.JTextField();
        txt_So_Luong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        Btn_Add = new javax.swing.JButton();
        txt_Balance = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Txt_ThanhTien = new javax.swing.JTextField();
        txt_pay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_Total = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton_Max = new javax.swing.JButton();
        jButton_Edit = new javax.swing.JButton();
        Print_excel = new javax.swing.JButton();
        jButton_Delele = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        btn_Print_PDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/image_Bill/icons8-billing-64.png"))); // NOI18N
        jLabel1.setText("Hoa don");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Time:");

        Lb_Date.setText("jLabel4");

        lb_Time.setText("jlabel5");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Buyer Details");

        jLabel7.setText("Name(Ten Khach Hang):");

        jLabel8.setText("So Thu Tu(ID):");

        jLabel9.setText("Ma Hang:");

        jLabel10.setText("Quatity(So Luong):");

        jLabel11.setText("Don Vi Tinh:");

        jLabel12.setText("Don Gia:");

        jLabel13.setText("Dien Thaoi:");

        jLabel14.setText("Dia Chi(Address):");

        txt_Don_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Don_giaActionPerformed(evt);
            }
        });
        txt_Don_gia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_Don_giaPropertyChange(evt);
            }
        });

        txt_So_Luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_So_LuongActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SoThutu(ID)", "Ten Khach", "Ma Hang", "Dai chi", "Dien Thoai", "Ngay_Thang_nam", "Don Vi", "So Luong", "Don Gia", "Thanh Tien"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/image_Bill/add.png"))); // NOI18N
        Btn_Add.setText("Add");
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        txt_Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BalanceActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Thanh Tien");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Pay(khach tra) :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Balance( Tra lai khach:");

        txt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_payActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baitap/image_Bill/Billing ani.gif"))); // NOI18N
        jLabel19.setText("jLabel19");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total");

        jLabel4.setText("Date");

        jButton1.setText("Tong thang 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Button Tong Tien cho Tat ca Hoa don thang2 =>");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Sap Xep danh sach theo thu tu giam dan tu thang 1 den thang 3");

        jButton2.setText("Sap Xep");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Nam 2022 co thu nhap tot nhat va mat hang ban duoc chay nhat cua quy do↓👇");

        jButton3.setText("Nam 2022 thu nhap tot nhat va hang chay nhat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel22.setText("Hoa don co gia tri Lon nhat Trong Ngay 5/04/2023↪");

        jButton_Max.setText("Max(5/04/2023");
        jButton_Max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MaxActionPerformed(evt);
            }
        });

        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        Print_excel.setText("Print Exel");
        Print_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_excelActionPerformed(evt);
            }
        });

        jButton_Delele.setText("Delete");
        jButton_Delele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleleActionPerformed(evt);
            }
        });

        jButton_Clear.setText("Clear");
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        btn_Print_PDF.setText("Print PDF");
        btn_Print_PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Print_PDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lb_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(lb_Time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Dien_thoai, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Date)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_so_thu_tu, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_MaHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Don_Vi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Print_excel)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Don_gia)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_So_Luong)
                .addGap(44, 44, 44)
                .addComponent(Btn_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Delele)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Print_PDF)
                .addGap(62, 62, 62))
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_ThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(txt_Total)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_pay))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Balance))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Max, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Lb_Date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lb_Time)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Diachi)
                            .addComponent(jLabel13)
                            .addComponent(txt_Dien_thoai)
                            .addComponent(jLabel14)
                            .addComponent(jLabel4)
                            .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Ten)
                            .addComponent(jLabel7))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_so_thu_tu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txt_MaHang)
                        .addComponent(jLabel11)
                        .addComponent(txt_Don_Vi)
                        .addComponent(Print_excel)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Don_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_So_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Add)
                    .addComponent(jButton_Edit)
                    .addComponent(jButton_Delele)
                    .addComponent(jButton_Clear)
                    .addComponent(btn_Print_PDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jButton_Max))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static Connection datacon;
    public static Connection getdatacon()
    {
        return datacon;
    }
    public static void Connectiondb()
    { //ham connnect to database;
        //System.out.println("Connecting database...");
        try{
            //Connection dataconnection ;
            Class.forName("com.mysql.jdbc.Driver");
            datacon = DriverManager.getConnection("jdbc:mysql://localhost:3306/quan_ly_hoa_don_bill","root","");
            System.out.println("Database connected!");
        } catch (ClassNotFoundException | SQLException e) {
            //JOptionPane.showMessageDialog(this, e);
            throw new IllegalStateException("Cannot connect the database!", e);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connectiondb();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {
            Statement s = getdatacon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet r = s.executeQuery("SELECT * FROM hoadon");
            DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
                //if(r.first()) neu khong lay id trong index 0 trong sql;
                //if(ten)
                while(r.next())
                {
                    String ID = r.getString(1);
                    String TenKhach_a = r.getString(2);
                    String Mahang = r.getString(3);
                    String Diachi_a = r.getString(4);
                    String DienThoai_a = r.getString(5);
                    String Date = r.getString(6);
                    String Donvi = r.getString(7);
                    String SoLuong_a = r.getString(8);
                    String Dongia = r.getString(9);
                    String Total_a = r.getString(10);
                    String st[]= {ID,TenKhach_a,Mahang,Diachi_a,DienThoai_a,Date,Donvi,Dongia,SoLuong_a,Total_a};
                    table.addRow(st);
                    //table.setRowCount(0); //delete
                }
            
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
        String TenKhach = txt_Ten.getText();
        String Diachi = txt_Diachi.getText();
        String DienThoai = txt_Dien_thoai.getText();
        String SoThuTu_ID = txt_so_thu_tu.getText();
        String MaHang = txt_MaHang.getText();
        String DonVi_Tinh = txt_Don_Vi.getText();
        String Date = txt_Date.getText();
        int SoLuong = Integer.parseInt(txt_So_Luong.getText());
        double Don_gia = Double.parseDouble(txt_Don_gia.getText());
        double ThanhTien = SoLuong*Don_gia;
        Txt_ThanhTien.setText(String.valueOf(ThanhTien));
        //

        try {
            
            Statement s = getdatacon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String sql = "INSERT INTO hoadon(ID,`Ten Khach`,`Ma Hang`,`Dia Chi`,`Dien thoai`,`Don vi`,`Don gia`,`So Luong`,Total,DATE) VALUES ('"+SoThuTu_ID+"','"+TenKhach+"','"+MaHang+"','"+Diachi+"','"+DienThoai+"','"+DonVi_Tinh+"','"+Don_gia+"','"+SoLuong+"','"+ThanhTien+"','"+Date+"')";
            s .execute(sql);
            JOptionPane.showMessageDialog(this, "Add successefuly");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
       
        try {
            String ten = txt_Ten.getText();
            
            Statement s = getdatacon().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet r = s.executeQuery("SELECT * FROM hoadon WHERE `Ten Khach`= '"+ten+"' ");
            DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
            table.setRowCount(0); //delete
                //if(r.first()) neu khong lay id trong index 0 trong sql;
                while(r.next())
                {
                    String ID = r.getString(1);
                    String TenKhach_a = r.getString(2);
                    String Mahang = r.getString(3);
                    String Diachi_a = r.getString(4);
                    String DienThoai_a = r.getString(5);
                    String Date_a = r.getString(6);
                    String Donvi = r.getString(7);
                    String SoLuong_a = r.getString(8);
                    String Dongia = r.getString(9);
                    String Total_a = r.getString(10);
                    String st[]= {ID,TenKhach_a,Mahang,Diachi_a,DienThoai_a,Date_a,Donvi,Dongia,SoLuong_a,Total_a};
                    table.addRow(st);
                }
            
      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        double sum = 0;
        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            sum +=Double.parseDouble(jTable1.getValueAt(i, 9).toString());
        }
        txt_Total.setText(Double.toString(sum));
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void txt_Don_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Don_giaActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_txt_Don_giaActionPerformed

    private void txt_Don_giaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_Don_giaPropertyChange
 // TODO add your handling code here:
    }//GEN-LAST:event_txt_Don_giaPropertyChange

    private void txt_So_LuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_So_LuongActionPerformed
        int SoLuong = Integer.parseInt(txt_So_Luong.getText());
        double Don_gia = Double.parseDouble(txt_Don_gia.getText());
        double ThanhTien = SoLuong*Don_gia;
        Txt_ThanhTien.setText(String.valueOf(ThanhTien));
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_So_LuongActionPerformed

    public void Balance()
    {
        double Total = Double.parseDouble(txt_Total.getText());
        double pay = Double.parseDouble(txt_pay.getText());
        double balance = pay - Total;
        txt_Balance.setText(String.valueOf(balance));
        
    }
    private void txt_BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BalanceActionPerformed

    private void txt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_payActionPerformed
        Balance();
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_payActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Main_2of_jfram_baiHoa_don.main(null);
            this.dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Main_3of_jfram_baiHoa_don.main(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Main_4of_jfram_baiHoa_don.main(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_MaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MaxActionPerformed
        Main_5of_jfram_baiHoa_don.main(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_MaxActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int id = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/quan_ly_hoa_don_bill","root","");
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet r = s.executeQuery("SELECT* FROM hoadon where id="+id);
            while(r.next())
            {//ID,`Ten Khach`,`Ma Hang`,`Dia Chi`,`Dien thoai`,`Don vi`,`Don gia`,`So Luong`,Total,DATE
                txt_so_thu_tu.setText(r.getString("ID"));
                txt_Ten.setText(r.getString(2));
                txt_MaHang.setText(r.getString(3));
                txt_Diachi.setText(r.getString(4));
                txt_Dien_thoai.setText(r.getString(5));
                txt_Date.setText(r.getString(6));
                txt_Don_Vi.setText(r.getString(7));
                txt_So_Luong.setText(r.getString(9));
                txt_Don_gia.setText(r.getString(8));
                Txt_ThanhTien.setText(r.getString(10));
            }
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_DeleleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleleActionPerformed
        int Id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        try {
            Connectiondb();
            Statement s = datacon.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            int r =JOptionPane.showConfirmDialog(this, "Are you sure to delete Selected row?");
            if(r==0){
                if(!s.execute("delete from hoadon Where id ="+Id))
                {
                    DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
                    table.setRowCount(0); //delete
                    formWindowOpened(null);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error! try again!!");
            }
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleleActionPerformed

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
         txt_so_thu_tu.setText("");
         txt_Date.setText("");
         txt_Ten.setText("");
         txt_MaHang.setText("");
         txt_Diachi.setText("");
         txt_Dien_thoai.setText("");
         txt_Don_Vi.setText("");
         txt_Don_gia.setText("");
         txt_So_Luong.setText("");
         Txt_ThanhTien.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        int Id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        try {//ID,`Ten Khach`,`Ma Hang`,`Dia Chi`,`Dien thoai`,`Don vi`,`Don gia`,`So Luong`,Total,DATE
            Connectiondb();
            Statement s = datacon.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            boolean b = s.execute("update hoadon set ID='"+txt_so_thu_tu.getText()+"',`Ten Khach`='"+txt_Ten.getText()+"',`Ma Hang`='"+txt_MaHang.getText()+"',`Dia Chi`='"+txt_Diachi.getText()+"',`Dien thoai`='"+txt_Dien_thoai.getText()+"',DATE='"+txt_Date.getText()+"',`Don vi`='"+txt_Don_Vi.getText()+"',`Don gia`='"+txt_Don_gia.getText()+"',`So Luong`='"+txt_So_Luong.getText()+"', Total='"+Txt_ThanhTien.getText()+"' where id="+Id);
            if(!b)
            {
                DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
                table.setRowCount(0); //delete
                formWindowOpened(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void btn_Print_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Print_PDFActionPerformed
        Document document = new Document();
        String path="";
        JFileChooser j=new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x=j.showSaveDialog(this);
        if(x==JFileChooser.APPROVE_OPTION)
        {
            path = j.getSelectedFile().getPath();
        }
        //Document doc = new Document();
        try 
        {
            PdfWriter.getInstance(document, new FileOutputStream(path+"abc.pdf"));
            document.open();
            PdfPTable tbl = new PdfPTable(2);
            tbl.addCell("ID");
            tbl.addCell("TEN");
            /*tbl.addCell("3");
            tbl.addCell("4");
            tbl.addCell("5");
            tbl.addCell("6");
            tbl.addCell("7");
            tbl.addCell("8");
            tbl.addCell("9");
            tbl.addCell("10");*/
            for(int i=0; i<jTable1.getRowCount(); i++)
            {
                String ID = jTable1.getValueAt(i, 0).toString();
                String Tenkh = jTable1.getValueAt(i, 1).toString();
                tbl.addCell(ID);
                tbl.addCell(Tenkh);
            }
            document.add(tbl);
            JOptionPane.showMessageDialog(this, "PDF Generated");
        } catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(this, e);
        }
        document.close();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Print_PDFActionPerformed

    private void Print_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_excelActionPerformed
   try {
        
        // create a workbook
        XSSFWorkbook wb = new XSSFWorkbook();  // xls file
        // create a new sheet
        XSSFSheet sheet = wb.createSheet("Foglio di Prova!");
        // declare a row object reference
        XSSFRow r = null;
        // declare a cell object reference
        Cell c = null;
        
        r = sheet.createRow(3);
        c = r.createCell(0,CellType.STRING);
        c.setCellValue("STT");
        
        c = r.createCell(1,CellType.STRING);
        c.setCellValue("TenKhach");
        
        c = r.createCell(2,CellType.STRING);
        c.setCellValue("Ma Hang");
        c = r.createCell(3,CellType.STRING);
        c.setCellValue("Diachi");
        c = r.createCell(4,CellType.STRING);
        c.setCellValue("DienThaoi");
        c = r.createCell(5,CellType.STRING);
        c.setCellValue("Date");
        c = r.createCell(6,CellType.STRING);
        c.setCellValue("DonVi");
        c = r.createCell(7,CellType.STRING);
        c.setCellValue("SoLuong");
        c = r.createCell(8,CellType.STRING);
        c.setCellValue("Don gia");
        c = r.createCell(9,CellType.STRING);
        c.setCellValue("Thanh Tien");
        
        // create a new file
        FileOutputStream fos;
        fos = new FileOutputStream("D://danhSach.xlsx");
        // create a sheet table rows
        TableModel model = jTable1.getModel();
        for(int i = 0; i < model.getRowCount(); i++) 
        {
            r = sheet.createRow(4 + i);
            for (int j = 0; j < model.getColumnCount(); j++) {
                c = r.createCell(j);
                c.setCellValue(model.getValueAt(i, j).toString()); // thiết lập giá trị cho ô
            }
        }
        wb.write(fos); // ghi dữ liệu ra file
        fos.close(); // đóng file
        JOptionPane.showMessageDialog(this, "Print to Exceled");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Some thing wrong!!");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_Print_excelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bai_Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bai_Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bai_Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bai_Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Bai_Hoa_Don().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Add;
    private javax.swing.JLabel Lb_Date;
    private javax.swing.JButton Print_excel;
    private javax.swing.JTextField Txt_ThanhTien;
    private javax.swing.JButton btn_Print_PDF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Delele;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_Max;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_Time;
    private javax.swing.JTextField txt_Balance;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_Diachi;
    private javax.swing.JTextField txt_Dien_thoai;
    private javax.swing.JTextField txt_Don_Vi;
    private javax.swing.JTextField txt_Don_gia;
    private javax.swing.JTextField txt_MaHang;
    private javax.swing.JTextField txt_So_Luong;
    private javax.swing.JTextField txt_Ten;
    private javax.swing.JTextField txt_Total;
    private javax.swing.JTextField txt_pay;
    private javax.swing.JTextField txt_so_thu_tu;
    // End of variables declaration//GEN-END:variables
}
